### ISSUE TITLE
Error on setting AC Mode for ID 1

### ISSUE THREAD

**Issue by tonymyatt** [tonymyatt/airtouch3pyapi#1]
Exception is raised when AC mode is set for AC Unit 1
```
Traceback (most recent call last):
  File "c:\Users\Engineering\Documents\GitHub\airtouch3api\demo.py", line 14, in <module>
    print(f"Mode for AC1 {at3.ac_units[1].set_mode(AT3AcMode.DRY)}")
  File "c:\Users\Engineering\Documents\GitHub\airtouch3api\airtouch3\airtouch3.py", line 106, in set_mode
    return self._at3.set_mode_ac_unit(self.number, mode)
  File "c:\Users\Engineering\Documents\GitHub\airtouch3api\airtouch3\airtouch3.py", line 223, in set_mode_ac_unit
    if not self._process_response(data): return None
  File "c:\Users\Engineering\Documents\GitHub\airtouch3api\airtouch3\airtouch3.py", line 378, in _process_response
    acUnit.mode = AT3AcMode(int(byte_value))
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 130 is not a valid AT3AcMode
```

**Comment by tonymyatt** [comment]
Resolved in v0.8
